[package]
name = "hig-cli"
version = "1.10.1"
edition.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
clap.workspace = true
dialoguer.workspace = true
hex.workspace = true
hig-core = { path = "../hig-core" }
serde.workspace = true
serde_json.workspace = true
walkdir.workspace = true
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
dunce.workspace = true
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "hig"
path = "src/main.rs"
